from linebot.models import (
    MessageEvent, TextMessage, StickerMessage, TextSendMessage, ImageSendMessage, StickerSendMessage, LocationSendMessage, TemplateSendMessage, ButtonsTemplate, PostbackAction, MessageAction, URIAction, CarouselTemplate, CarouselColumn, QuickReply, QuickReplyButton
)
faq = {
    '貼圖': StickerSendMessage(
        package_id='11537',
        sticker_id='52002758'
    ),
    '捷運': ImageSendMessage(
        original_content_url='https://web.metro.taipei/pages/assets/images/routemap2020.png',
        preview_image_url='https://web.metro.taipei/pages/assets/images/routemap2020.png'
    ),
    '雨量': ImageSendMessage(
        original_content_url='https://cwbopendata.s3.ap-northeast-1.amazonaws.com/DIV2/O-A0040-002.jpg',
        preview_image_url='https://cwbopendata.s3.ap-northeast-1.amazonaws.com/DIV2/O-A0040-002.jpg'
    ),
    '溫度': ImageSendMessage(
        original_content_url='https://cwbopendata.s3.ap-northeast-1.amazonaws.com/DIV2/O-A0038-001.jpg',
        preview_image_url='https://cwbopendata.s3.ap-northeast-1.amazonaws.com/DIV2/O-A0038-001.jpg'
    ),
    '雷達回波圖': ImageSendMessage(
        original_content_url='https://cwbopendata.s3.ap-northeast-1.amazonaws.com/MSC/O-A0058-003.png',
        preview_image_url='https://cwbopendata.s3.ap-northeast-1.amazonaws.com/MSC/O-A0058-003.png'
    ),
    '空氣品質': TextSendMessage(
        text='請選擇縣市或測站',
        quick_reply=QuickReply(
            items=[
                QuickReplyButton(
                    action=MessageAction(label="縣市", text="縣市")
                ),
                QuickReplyButton(
                    action=MessageAction(label="測站", text="測站")
                )
            ]
        )
    ),
    '天氣預報': TextSendMessage(
        text='請選擇縣市',
        quick_reply=QuickReply(
            items=[
                QuickReplyButton(
                    action=MessageAction(label="縣市", text="縣市")
                )
            ]
        )
    ),
    '測站': TextSendMessage(
            text="請輸入要查詢的測站:\nHint:\n基隆, 汐止, 萬里, 新店, \n土城, 板橋, 新莊, 菜寮, \n林口, 淡水, 士林, 中山, \n萬華, 古亭, 松山, 大同, \n桃園, 大園, 觀音, 平鎮, \n龍潭, 湖口, 竹東, 新竹, \n頭份, 苗栗, 三義, 豐原, \n沙鹿, 大里, 忠明, 西屯,\n彰化, 線西, 二林, 南投, \n斗六, 崙背, 新港, 朴子, \n臺西, 嘉義, 新營, 善化, \n安南, 臺南, 美濃, 橋頭, \n仁武, 鳳山, 大寮, 林園, \n楠梓, 左營, 前金, 前鎮, \n小港, 屏東, 潮州, 恆春, \n 臺東, 花蓮, 陽明, 宜蘭, \n冬山, 三重, 中壢, 竹山, \n永和, 復興, 埔里, 馬祖, \n 金門, 馬公, 關山, 麥寮, \n富貴角, 大城, 高雄(湖內), \n臺南(麻豆), 屏東(琉球), \n桃園(三民), 新北(樹林), \n臺南(學甲), 屏東(枋寮)"
        ),
    '縣市': TemplateSendMessage(
        alt_text='Carousel template',
        template=CarouselTemplate(
            columns=[
                CarouselColumn(
                    thumbnail_image_url='https://i.picsum.photos/id/653/2509/1673.jpg?hmac=FyGKup0jkF1OQ38Auws_u2cuUCBKbRc6rE04Z3d3CNo',
                    title='縣市選單一',
                    text='點選下方按鈕查詢',
                    actions=[
                        MessageAction(
                            label='基隆市',
                            text='基隆市'
                        ),
                        MessageAction(
                            label='新北市',
                            text='新北市'
                        ),
                        MessageAction(
                            label='臺北市',
                            text='臺北市'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='https://i.picsum.photos/id/1067/5760/3840.jpg?hmac=gO_V7rUFdM8YddyLysCQet4CS0CzSvUcfAtHI1ismLM',
                    title='縣市選單二',
                    text='點選下方按鈕查詢',
                    actions=[
                        MessageAction(
                            label='桃園市',
                            text='桃園市'
                        ),
                        MessageAction(
                            label='新竹縣',
                            text='新竹縣'
                        ),
                        MessageAction(
                            label='新竹市',
                            text='新竹市'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='https://i.picsum.photos/id/583/2509/1673.jpg?hmac=X9Eq9t1mgiV81aQpccy4e5e0xwXtn105qHpFs3THDB4',
                    title='縣市選單三',
                    text='點選下方按鈕查詢',
                    actions=[
                        MessageAction(
                            label='苗栗縣',
                            text='苗栗縣'
                        ),
                        MessageAction(
                            label='臺中市',
                            text='臺中市'
                        ),
                        MessageAction(
                            label='彰化縣',
                            text='彰化縣'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='https://i.picsum.photos/id/653/2509/1673.jpg?hmac=FyGKup0jkF1OQ38Auws_u2cuUCBKbRc6rE04Z3d3CNo',
                    title='縣市選單四',
                    text='點選下方按鈕查詢',
                    actions=[
                        MessageAction(
                            label='南投縣',
                            text='南投縣'
                        ),
                        MessageAction(
                            label='雲林縣',
                            text='雲林縣'
                        ),
                        MessageAction(
                            label='嘉義縣',
                            text='嘉義縣'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='https://i.picsum.photos/id/1067/5760/3840.jpg?hmac=gO_V7rUFdM8YddyLysCQet4CS0CzSvUcfAtHI1ismLM',
                    title='縣市選單五',
                    text='點選下方按鈕查詢',
                    actions=[
                        MessageAction(
                            label='嘉義市',
                            text='嘉義市'
                        ),
                        MessageAction(
                            label='臺南市',
                            text='臺南市'
                        ),
                        MessageAction(
                            label='高雄市',
                            text='高雄市'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='https://i.picsum.photos/id/583/2509/1673.jpg?hmac=X9Eq9t1mgiV81aQpccy4e5e0xwXtn105qHpFs3THDB4',
                    title='縣市選單六',
                    text='點選下方按鈕查詢',
                    actions=[
                        MessageAction(
                            label='屏東縣',
                            text='屏東縣'
                        ),
                        MessageAction(
                            label='臺東縣',
                            text='臺東縣'
                        ),
                        MessageAction(
                            label='花蓮縣',
                            text='花蓮縣'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='https://i.picsum.photos/id/653/2509/1673.jpg?hmac=FyGKup0jkF1OQ38Auws_u2cuUCBKbRc6rE04Z3d3CNo',
                    title='縣市選單七',
                    text='點選下方按鈕查詢',
                    actions=[
                        MessageAction(
                            label='宜蘭縣',
                            text='宜蘭縣'
                        ),
                        MessageAction(
                            label='連江縣',
                            text='連江縣'
                        ),
                        MessageAction(
                            label='金門縣',
                            text='金門縣'
                        )
                    ]
                ),
                CarouselColumn(
                    thumbnail_image_url='https://i.picsum.photos/id/1067/5760/3840.jpg?hmac=gO_V7rUFdM8YddyLysCQet4CS0CzSvUcfAtHI1ismLM',
                    title='縣市選單八',
                    text='點選下方按鈕查詢',
                    actions=[
                        MessageAction(
                            label='澎湖縣',
                            text='澎湖縣'
                        ),
                        MessageAction(
                            label='...',
                            text='...'
                        ),
                        MessageAction(
                            label='...',
                            text='...'
                        )
                    ]
                )
            ]
        )
    )
}

menu = TemplateSendMessage(
    alt_text='Carousel template',
    template=CarouselTemplate(
        columns=[
            CarouselColumn(
                thumbnail_image_url='https://i.picsum.photos/id/109/4287/2392.jpg?hmac=K5ytllhfakgsUEDFnY5ujHIGJTzELPQgVJjZMpRlfJY',
                title='天氣即時圖',
                text='點選下方按鈕開始互動',
                actions=[
                    MessageAction(
                        label='日累積雨量圖(小間距)',
                        text='雨量'
                    ),
                    MessageAction(
                        label='溫度分布圖',
                        text='溫度'
                    ),
                    MessageAction(
                        label='雷達整合回波圖',
                        text='雷達回波圖'
                    )
                ]
            ),
            CarouselColumn(
                thumbnail_image_url='https://i.picsum.photos/id/970/3264/2448.jpg?hmac=aH-hIUJyFxqFreKtIQ62w6IKGr47AUC40nAKne0VHGE',
                title='天氣概況',
                text='點選下方按鈕開始互動',
                actions=[
                    MessageAction(
                        label='天氣預報(未來8小時)',
                        text='天氣預報'
                    ),
                    MessageAction(
                        label='空氣品質',
                        text='空氣品質'
                    ),
                    URIAction(
                        label='交通部中央氣象局',
                        uri='https://www.cwb.gov.tw/V8/C/'
                    )
                ]
            )
        ]
    )
)
